### ISSUE TITLE
TM4 to TM2 converter errors

### ISSUE THREAD

**Issue by thorsilver** [adamyedidia/parsimony#3]
Hi!  So I cloned this repository earlier tonight and wanted to test out Laconic, so I duplicated riemann.lac and compiled it to TMD -- that went fine, could simulate it.  Could compile it also to TM4, but couldn't simulate it.  Then found I couldn't compile to TM2, or compile any of the other example files.  After some mucking about I made some changes that got TM4 simulating just fine, but TM2 is still not working for me, and says this:

Traceback (most recent call last):
  File "tm4_to_tm2_converter.py", line 300, in <module>
    for outerState in sttm.listOfRealStates:
AttributeError: 'SingleTapeTuringMachine' object has no attribute 'listOfRealStates'

Followed by a whole bunch of other errors.  Any idea what may be causing this?  I'm on Mac OS, TMD and TM4 compilation/simulation work fine now as I said, it's only TM2 that's broken for me.

**Comment by adamyedidia** [comment]
Hi Thorsilver,

Thank you very much for the bug report! I don't know what caused that bug to be introduced, but it should be fixed now.

Happy Turing Machining!

-Adam

**Comment by thorsilver** [comment]
Everything does indeed compile and run perfectly now :)  Thanks for responding so quickly, and for your hard work putting Laconic together!
