### ISSUE TITLE
Does this support recursive function call?

### ISSUE THREAD

**Issue by YouhuaLi** [adamyedidia/parsimony#4]
I created a simple lac file to calculate factorial in a recursive way:
https://github.com/YouhuaLi/parsimony/blob/master/src/laconic/laconic_files/factorial.lac

In interprete phase, the code works well:
`cayvryli:laconic_meta yli$python2 laconic_interpreter.py factorial
r: 93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000
Program halted without errors.`

But I got the error when I compiled it:

`(⎈ |p1.kube.demonware.net:prod-mw)cayvryli:laconic_meta yli$python2 laconic_to_4s_tm_compiler.py factorial
Compiling to TMD...
Traceback (most recent call last):
  File "compiler_helper.py", line 22, in <module>
    main(sys.argv)
  File "compiler_helper.py", line 19, in main
    walker.walk(writer, tree)
  File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
    self.walk(listener, child)
  File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
    self.walk(listener, child)
  File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
    self.walk(listener, child)....`

Does this whole thing support recursive function calls? 
I really want to have recursive support and have some cool ideas if I can do recursive function calls in a turning machine program.

Thanks.

**Comment by YouhuaLi** [comment]
I will do more study on this.

**Comment by adamyedidia** [comment]
Hi Youhua,

Sorry for the late reply—I have been working on my PhD thesis, but should
have time later this week to think about Laconic. Did you figure out what
the bug was?

Best,
-Adam

**Comment by YouhuaLi** [comment]
hi Adam,
    thanks for your reply!
I haven't found out what the issue really is. the full error message is:

> yli$python2 laconic_to_tmd_compiler.py factorial
> Compiling to TMD...
> Traceback (most recent call last):
>   File "compiler_helper.py", line 22, in <module>
>     main(sys.argv)
>   File "compiler_helper.py", line 19, in main
>     walker.walk(writer, tree)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
>     self.walk(listener, child)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
>     self.walk(listener, child)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
>     self.walk(listener, child)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
>     self.walk(listener, child)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
>     self.walk(listener, child)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
>     self.walk(listener, child)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 172, in walk
>     self.walk(listener, child)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 170, in walk
>     self.enterRule(listener, t)
>   File "/Library/Python/2.7/site-packages/antlr4/tree/Tree.py", line 184, in enterRule
>     ctx.enterRule(listener)
>   File "/Users/yli/code/parsimony/src/laconic/laconic_meta/LaconicParser.py", line 947, in enterRule
>     listener.enterFuncproccall(self)
>   File "/Users/yli/code/parsimony/src/laconic/laconic_meta/codewriter.py", line 124, in enterFuncproccall
>     for i in range(self.funcAuxCountDictionary[funcProcName]):
> KeyError: u'factorial'
> Importing dependencies...
> main
> Done!

so it's from line 124 of [codewriter.py](https://github.com/adamyedidia/parsimony/blob/7c199dbe0c82f0b9cc1adfbdc2b48fee3fef53aa/src/laconic/laconic_meta/codewriter.py#L124).  Looks like it's looking up already defined functions?

While I saw you put some recursive function example in https://github.com/adamyedidia/parsimony/tree/master/src/tmd/tmd_dirs/example_tmd_dir, I wonder if this are compiled from laconic or created manually?

Kind Regards
Youhua

**Comment by adamyedidia** [comment]
Hi Youhua,

Thanks a lot for your patience. No, the compiler doesn't support
recursive function calls, as you guessed; in fact, it doesn't even support
function definitions that are in the wrong order (for example, in the
below, the program wouldn't compile if the factorial definition was above
the decr definition)! Confusingly, the interpreter can handle both these
things, but not the compiler. To do factorial non-recursively, you can do:
/* caculate factoiral in a recursive way */

func decr(x) {
    x = x - 1;
    return;
}

func factorial(n, r) {
    while (n > 0 ) {
    r = n * r;
    decr(n);
    }
    return;
}

int n;
int r;

n = 6;
r = 1;

factorial(n, r);
print r;

halt;

But I'm guessing you were interested in something more sophisticated that
could handle recursion. Unfortunately, I think you're just out of luck
there--hopefully there's something equivalent you can do using a while loop?

Best,
-Adam

**Comment by YouhuaLi** [comment]
Thanks for your clarification. now I understand and will do more study. Also your project is really cool.

**Comment by adamyedidia** [comment]
Thank you!
